# Generated by Django 3.1.7 on 2021-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
