# Generated by Django 3.1.7 on 2021-05-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_voucher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='destinationCity',
        ),
    ]
