# Generated by Django 3.1.7 on 2021-06-06 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_voucher_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('vouchers', models.IntegerField()),
                ('price', models.FloatField()),
                ('creationDate', models.DateTimeField(default=datetime.datetime(2021, 6, 6, 23, 0, 12, 687119))),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='status',
        ),
    ]
