# Generated by Django 3.1.7 on 2021-06-07 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_auto_20210606_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDishes', models.PositiveIntegerField(default=0)),
                ('finalPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('inOrder', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 21, 39, 38, 181123)),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('finalPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_dishes', to='testApp.cart')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.voucher')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='testApp.CartProduct'),
        ),
    ]
